spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/learn_kotlin
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect

pagination:
  page:
    size:
      default: 2
